before:
  hooks:
    - go mod tidy
    - go generate ./...
    - pre-commit run --all-files --verbose
builds:
  - id: api
    dir: cmd/gopkgs-api
    binary: gopkgs-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: import-server
    dir: cmd/import-server
    binary: import-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - id: gopkgs-api
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.api
    ids:
      - api
    image_templates:
      # - "devnw/gopkgs-api:latest"
      # - "devnw/gopkgs-api:{{ .Tag }}"
      # - "devnw/gopkgs-api:v{{ .Major }}"
      # - "gcr.io/gopkgs-342114/gopkgs/api:latest"
      - "ghcr.io/devnw/gopkgs-api:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=Go Packages API"
      - "--label=org.opencontainers.image.description="
      - "--label=org.opencontainers.image.authors=info@devnw.com"
      - "--label=org.opencontainers.image.url=https://gopkgs.org"
      - "--label=org.opencontainers.image.source=https://github.com/devnw/srv.gopkgs.org"
      - "--label=org.opencontainers.image.documentation=https://gopkgs.org/docs"
      - "--label=org.opencontainers.image.licenses=Apache 2.0"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
  - id: import-server
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.is
    ids:
      - import-server
    image_templates:
      # - "devnw/import-server:latest"
      # - "devnw/import-server:{{ .Tag }}"
      # - "devnw/import-server:v{{ .Major }}"
      # - "gcr.io/gopkgs-342114/gopkgs/import-server:latest"
      - "ghcr.io/devnw/import-server:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=Go Packages Import Server"
      - "--label=org.opencontainers.image.description="
      - "--label=org.opencontainers.image.authors=info@devnw.com"
      - "--label=org.opencontainers.image.url=https://gopkgs.org"
      - "--label=org.opencontainers.image.source=https://github.com/devnw/srv.gopkgs.org"
      - "--label=org.opencontainers.image.documentation=https://gopkgs.org/docs"
      - "--label=org.opencontainers.image.licenses=Apache 2.0"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
